name: PHP CS Fixer

on: [ push ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, php-cs-fixer

      - name: Run phpcs
        run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
