name: PHP CS Fixer

on: [ push ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, phpcs

      - name: Run phpcs
        run: phpcs --report=checkstyle | cs2pr
